# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# admin users
u = User.new name: 'Gustavo', last_names: 'Beauregard', mail: 'gbn@mit.edu'
u.list_perms = u.add_perms = u.edit_perms = u.delete_perms = User.all_perms
u.set_password "123456", "123456"
u.save

u = User.new name: 'Ana', last_names: 'Mendez', mail: 'amendezr@mit.edu'
u.list_perms = u.add_perms = u.edit_perms = u.delete_perms = User.all_perms
u.set_password "123456", "123456"
u.save

# user functions
def save_user(user)
  user_perms = { list_perms: 15, add_perms: 8, edit_perms: 8, delete_perms: 8 }
  user_password = "mituser"
  user.set_password user_password, user_password
  user_perms.each do |name, val|
    user.send("#{name}=", val)
  end
  user.save
end

# users
u = User.new(name: 'Angela', last_names: 'Wang', mail: 'yinjwang@mit.edu')
save_user(u)
u = User.new(name: 'Alexander', last_names: 'Oliva', mail: 'alex93@mit.edu')
save_user(u)
u = User.new(name: 'Paola', last_names: 'Ruiz', mail: 'pruiz@mit.edu')
save_user(u)
u = User.new(name: 'Yachi', last_names: 'Chang', mail: 'changycj@mit.edu')
save_user(u)
u = User.new(name: 'Jamal', last_names: 'Elkhader', mail: 'elkhader@mit.edu')
save_user(u)
u = User.new(name: 'Erin', last_names: 'Kenney', mail: 'ekenney@mit.edu')
save_user(u)
u = User.new(name: 'Kirsten', last_names: 'Augdahl', mail: 'kaugdahl@mit.edu')
save_user(u)
u = User.new(name: 'Margo', last_names: 'Dawes', mail: 'mdawes@mit.edu')
save_user(u)
u = User.new(name: 'Aishwarya', last_names: 'Narayan', mail: 'aishn@mit.edu')
save_user(u)
u = User.new(name: 'Lesley', last_names: 'Wang', mail: 'leswang@mit.edu')
save_user(u)

# upload configs
uc = UploadConfig.new max_size: 307200, allowed_extensions: 'jpg,png'
uc.identity = Admin::UploadConfig::Identity::CountryImage
uc.save



# countries
Country.create(name: 'Afghanistan')
Country.create(name: 'Albania')
Country.create(name: 'Algeria')
Country.create(name: 'Andorra')
Country.create(name: 'Angola')
Country.create(name: 'Antigua and Barbuda')
Country.create(name: 'Argentina')
Country.create(name: 'Armenia')
Country.create(name: 'Aruba')
Country.create(name: 'Australia')
Country.create(name: 'Austria')
Country.create(name: 'Azebaijan')
Country.create(name: 'Bahamas')
Country.create(name: 'Bahrain')
Country.create(name: 'Bangladesh')
Country.create(name: 'Barbados')
Country.create(name: 'Belarus')
Country.create(name: 'Belgium')
Country.create(name: 'Belize')
Country.create(name: 'Benin')
Country.create(name: 'Bhutan')
Country.create(name: 'Bolivia')
Country.create(name: 'Bosnia and Herzegovina')
Country.create(name: 'Botswana')
Country.create(name: 'Brazil')
Country.create(name: 'Brunei')
Country.create(name: 'Bulgaria')
Country.create(name: 'Burkina Faso')
Country.create(name: 'Burma')
Country.create(name: 'Burundi')
Country.create(name: 'Cambodia')
Country.create(name: 'Cameroon')
Country.create(name: 'Canada')
Country.create(name: 'Cape Verde')
Country.create(name: 'Central African Republic')
Country.create(name: 'Chad')
Country.create(name: 'Chile')
Country.create(name: 'China')
Country.create(name: 'Colombia')
Country.create(name: 'Comoros')
Country.create(name: 'Congo')
Country.create(name: 'Costa Rica')
Country.create(name: 'Cote d´Ivoire')
Country.create(name: 'Croatia')
Country.create(name: 'Cuba')
Country.create(name: 'Curacao')
Country.create(name: 'Cyprus')
Country.create(name: 'Czech Republic')
Country.create(name: 'Denmark')
Country.create(name: 'Djibouti')
Country.create(name: 'Dominica')
Country.create(name: 'Dominican Republic')
Country.create(name: 'East Timor')
Country.create(name: 'Ecuador')
Country.create(name: 'Egypt')
Country.create(name: 'El Salvador')
Country.create(name: 'Equatorial Guinea')
Country.create(name: 'Eritrea')
Country.create(name: 'Estonia')
Country.create(name: 'Ethiopia')
Country.create(name: 'Fiji')
Country.create(name: 'Finland')
Country.create(name: 'France')
Country.create(name: 'Gabon')
Country.create(name: 'The Gambia')
Country.create(name: 'Georgia')
Country.create(name: 'Germany')
Country.create(name: 'Ghana')
Country.create(name: 'Greece')
Country.create(name: 'Grenada')
Country.create(name: 'Guatemala')
Country.create(name: 'Guinea')
Country.create(name: 'Guinea-Bissau')
Country.create(name: 'Guyana')
Country.create(name: 'Haiti')
Country.create(name: 'Holy See')
Country.create(name: 'Honduras')
Country.create(name: 'Hong Kong')
Country.create(name: 'Hungary')
Country.create(name: 'Iceland')
Country.create(name: 'India')
Country.create(name: 'Indonesia')
Country.create(name: 'Iran')
Country.create(name: 'Iraq')
Country.create(name: 'Ireland')
Country.create(name: 'Israel')
Country.create(name: 'Italy')
Country.create(name: 'Jamaica')
Country.create(name: 'Japan')
Country.create(name: 'Jordan')
Country.create(name: 'Kazakhstan')
Country.create(name: 'Kenya')
Country.create(name: 'Kiribati')
Country.create(name: 'Kosovo')
Country.create(name: 'Kuwait')
Country.create(name: 'Kyrgyzstan')
Country.create(name: 'Laos')
Country.create(name: 'Latvia')
Country.create(name: 'Lebanon')
Country.create(name: 'Lesotho')
Country.create(name: 'Liberia')
Country.create(name: 'Libya')
Country.create(name: 'Liechtsenstein')
Country.create(name: 'Lithuania')
Country.create(name: 'Luxembourg')
Country.create(name: 'Macau')
Country.create(name: 'Macedonia')
Country.create(name: 'Madagascar')
Country.create(name: 'Malawi')
Country.create(name: 'Malaysia')
Country.create(name: 'Maldives')
Country.create(name: 'Mali')
Country.create(name: 'Malta')
Country.create(name: 'Marshall Islands')
Country.create(name: 'Mauritania')
Country.create(name: 'Mauritius')
Country.create(name: 'Mexico')
Country.create(name: 'Micronesia')
Country.create(name: 'Moldova')
Country.create(name: 'Monaco')
Country.create(name: 'Mongolia')
Country.create(name: 'Montenegro')
Country.create(name: 'Morocco')
Country.create(name: 'Mozambique')
Country.create(name: 'Namibia')
Country.create(name: 'Nauru')
Country.create(name: 'Nepal')
Country.create(name: 'Netherlands')
Country.create(name: 'Netherlands Antilles')
Country.create(name: 'New Zealand')
Country.create(name: 'Nicaragua')
Country.create(name: 'Niger')
Country.create(name: 'Nigeria')
Country.create(name: 'North Korea')
Country.create(name: 'Norway')
Country.create(name: 'Oman')
Country.create(name: 'Pakistan')
Country.create(name: 'Palau')
Country.create(name: 'Palestinian Territories')
Country.create(name: 'Panama')
Country.create(name: 'Papua New Guinea')
Country.create(name: 'Paraguay')
Country.create(name: 'Peru')
Country.create(name: 'Philippines')
Country.create(name: 'Poland')
Country.create(name: 'Portugal')
Country.create(name: 'Qatar')
Country.create(name: 'Romania')
Country.create(name: 'Russia')
Country.create(name: 'Rwanda')
Country.create(name: 'Saint Kitts and Nevis')
Country.create(name: 'Saint Lucia')
Country.create(name: 'Saint Vincent and the Grenadines')
Country.create(name: 'Samoa')
Country.create(name: 'San Marino')
Country.create(name: 'Sao Tome and Principe')
Country.create(name: 'Saudi Arabia')
Country.create(name: 'Senegal')
Country.create(name: 'Serbia')
Country.create(name: 'Seychelles')
Country.create(name: 'Singapore')
Country.create(name: 'Sint Maarten')
Country.create(name: 'Slovakia')
Country.create(name: 'Slovenia')
Country.create(name: 'Solomon Islands')
Country.create(name: 'Somalia')
Country.create(name: 'South Africa')
Country.create(name: 'South Korea')
Country.create(name: 'South Sudan')
Country.create(name: 'Spain')
Country.create(name: 'Sri Lanka')
Country.create(name: 'Sudan')
Country.create(name: 'Suriname')
Country.create(name: 'Swaziland')
Country.create(name: 'Sweden')
Country.create(name: 'Switzerland')
Country.create(name: 'Syria')
Country.create(name: 'Taiwan')
Country.create(name: 'Tajikistan')
Country.create(name: 'Tanzania')
Country.create(name: 'Thailand')
Country.create(name: 'Timor-Leste')
Country.create(name: 'Togo')
Country.create(name: 'Tongo')
Country.create(name: 'Trinidad and Tobago')
Country.create(name: 'Tunisia')
Country.create(name: 'Turkey')
Country.create(name: 'Turkmenistan')
Country.create(name: 'Tavalu')
Country.create(name: 'Uganda')
Country.create(name: 'Ukraine')
Country.create(name: 'United Arab Emirates')
Country.create(name: 'United Kingdom')
Country.create(name: 'US')
Country.create(name: 'Uruguay')
Country.create(name: 'Uzbekistan')
Country.create(name: 'Vanuatu')
Country.create(name: 'Venezuela')
Country.create(name: 'Vietnam')
Country.create(name: 'Yemen')
Country.create(name: 'Zambia')
Country.create(name: 'Zimbabwe')

# city functions
def save_city(city, country_name)
  country = Country.where(name: country_name).first
  if country.nil?
    puts "country not found: #{country}"
  else
    city.country_id = country.id
    city.save
  end
end

# cities
c = City.new(name: 'Mexico City', lat: 19.432608, lng: -99.133208)
save_city(c, 'Mexico')
c = City.new(name: 'Madrid', lat: 40.416775, lng: -3.70379)
save_city(c, 'Spain')
c = City.new(name: 'Sao Paulo', lat: -23.548943, lng: -46.638818)
save_city(c, 'Brazil')
c = City.new(name: 'Beijing', lat: 39.904030041601466, lng: 116.40752591192722)
save_city(c, 'China')
c = City.new(name: 'Kuala Lumpur', lat: 3.139003, lng: 101.686855)
save_city(c, 'Malaysia')


# languages
Language.create(name: 'Arabic')
Language.create(name: 'Awadhi')
Language.create(name: 'Azerbaijani')
Language.create(name: 'Bengali')
Language.create(name: 'Bhojpuri')
Language.create(name: 'Burmese')
Language.create(name: 'Chinese, Gan')
Language.create(name: 'Chinese, Hakka')
Language.create(name: 'Chinese, Jinyu')
Language.create(name: 'Chinese, Mandarin')
Language.create(name: 'Chinese, Min Nan')
Language.create(name: 'Chinese, Wu')
Language.create(name: 'Chinese, Xiang')
Language.create(name: 'Cantonese')
Language.create(name: 'Dutch')
Language.create(name: 'English')
Language.create(name: 'French')
Language.create(name: 'German')
Language.create(name: 'Gujarati')
Language.create(name: 'Hausa')
Language.create(name: 'Hindi')
Language.create(name: 'Italian')
Language.create(name: 'Japanese')
Language.create(name: 'Javanese')
Language.create(name: 'Kannada')
Language.create(name: 'Korean')
Language.create(name: 'Maithili')
Language.create(name: 'Malayalam')
Language.create(name: 'Marathi')
Language.create(name: 'Oriya')
Language.create(name: 'Panjabi')
Language.create(name: 'Persian')
Language.create(name: 'Polish')
Language.create(name: 'Portuguese')
Language.create(name: 'Romanian')
Language.create(name: 'Russian')
Language.create(name: 'Serbo-Croatian')
Language.create(name: 'Sindhi')
Language.create(name: 'Spanish')
Language.create(name: 'Sunda')
Language.create(name: 'Tamil')
Language.create(name: 'Telgu')
Language.create(name: 'Thai')
Language.create(name: 'Turkish')
Language.create(name: 'Ukrarian')
Language.create(name: 'Urdu')
Language.create(name: 'Vientamese')
Language.create(name: 'Yoruba')